### ISSUE TITLE
Unable to scan with Scan Option

### ISSUE THREAD

**Issue by DanPatten** [socs-dev-env/DoSOCS#29] opened 2015-03-17 23:45 UTC
If a scan is done with the parameter --scanOption fossology and a file is not in cache, it ignores the scanOption and performs a Ninka scan instead:

Fix for this is by modifying spdx.dy line 363:
```
tempFileInfo.populateFileInfo(scanOption)
```

**Comment by zwmcfarland** [comment] 2015-03-20 23:32
Line 363 already contains this. Maybe someone else fixed it and forgot to close the issue?

![image](https://cloud.githubusercontent.com/assets/6517665/6762501/75378af2-cf2f-11e4-9205-c93cf7012245.png)

In the case that I am not understanding please let me know.

**Closed by zwmcfarland** 2015-03-20 23:32 UTC

**Comment by DanPatten** [comment] 2015-03-21 00:08
In my tests it only worked after removing the "self." from that line. Try doing a test with fossology scanOption and the package not in cache with a bad Ninka path to confirm this.

**Comment by DanPatten** [comment] 2015-03-27 03:49
Any ETA on this issue?

**Comment by ttgurney** [comment] 2015-03-27 16:11
Dan, I was unable to reproduce this. I used a fresh install of DoSOCS with NINKA_PATH set to `/nonexistent`, FOSSOLOGY_PATH set to the correct nomos location, and database with no data. Here's the command line I used:

`./DoSPDX.py -p package.tar.bz2 --scan --scanOption fossology --print json`

Worked as expected, producing SPDX document output with license information from FOSSology.

**Comment by zwmcfarland** [comment] 2015-03-28 23:10
Fixed https://github.com/socs-dev-env/DoSOCS/commit/630971ea54907c1fe212833c8db2e5b3361bb186
